language: node_js
services:
- docker
- mongo
node_js:
- '10.0'
before_install:
- npm install npm@latest pm2 pon jsdoc -g
install:
- npm install
script:
- pon prepare
- pon build
deploy:
  provider: npm
  email: oss@realglobe.jp
  api_key:
    secure: k+DAOc3EfA6nF9ayna/aVaNOAZdNj19RBLGPwnKi9kDJd+Pea4ENPWFRSLrPVQBfcbkHK3xZW7RyKvSZ/tNlkWWbNbjaVJ+zza4JCx664nrNuB6EGaADsgJ80dokmf2wl5lR2X8Saw85vUAayzUtwcO0ZZB5YURLqmfIXRu2H18OfYWy0Bria5pow+ai1e82i25eemI4vTcx9LfwykXXIjYoB1ipm8gEpXCGqeq4c4knlhrieeXRdX7UYuYX+2bORJyQbx0HgdzP8HtkRvCcGBliCwDOAeeqmoA7gNzgmpX45oARZ3vFM1gZnw1aqchdytqmtsaO4WBMzSPrR4uGarvCBAMH/Rvk4A8sA9ooA3Kw5qN3bkyQe/BuZ0n7ZlQv3twVQjeqEx2R1Q6MFRiirVj8CZtfzoeRE4ZDrjd6BlOmC5te0dYIUNLvReSgCBXrCrn206JaQ2ZqfOMiMzVvU/0i3gFO4GbaDEn68akJkySMp927E/j2jEUfKQb+de8u8AVDCdec0/EHhA6aruKYSmq1HfdyRQ7l3AeFZEcdQz1xxmpErhTe2h/kdjkPIYemMJvXIAKCHKx9PLnrpysMr4lB56GCapoFYUmQs29fNg2yv/wEh79smJDeIMZGjBV9epBLWPHWEGd6XXxGVTzHclxW13fn79eu3cRytHSTwow=
