language: node_js
services:
- docker
- mongo
node_js:
- '10'
before_install:
- npm install pm2 pon jsdoc -g
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- rm -rf var
install:
- npm install
script:
- pon prepare
- pon build
after_success:
- ./misc/travis/publish.js
env:
  secure: "yMnOq7ZPG7U10/uTK6TsTclnWLXv2VGlWhv89GAyyawrXESAEf/2IJx0i3JcF6mDkQmUYfDAt9ltBEuYaYRTzwPaV5IMabADLlzq8kGlHIX84M5XWwBVwdy0KvCKVcEYU3KJDNVxK+FsOCu2i7sP3pIcsB9uhC2FQ728x4koDRJzhK5C80YUacdpbxECrnqiHboEkYLbqleqmGEjNwjPnXWMeXFx/levPX18D3nBfpi8KkNFS4iBrO3C4/Wxmkyv1AoSBaDL35jgSo8E2m5UQDIPjt7VsqG1iGIdCLNM8Mwh6aPcSWIpFThxwzKyu7dTXoEycfNvdEgQEXLlypt09c9TlOaZxHlkjJkpXfvVCtR3baxabsbYs1+cTmM1W8YwlwaqvAh12sLPgNucP4md+h5E928FgObHvwlNhQjS6TWih83LiVd0T5W9Z2iFIlL9ddWLwkMDOaGvxp9KDdQNcP8nC8lUq7tfslelZYmIW+OOt4liBY7CrL3WxRbdE6IFty3En6lLUZMC+bqZJF5aEUtAugPK06W0bdONaNA8nIQZvjocMFScpvErbIQTc4YuP/Q1zbraWW0aLzNMQrsWLECZ1P6Nn/4ww2t8bmmitje7BOmKFU/lUM4Sqf+fyvR3M1M2dNDjn12ThLMfgAdJQJRdOsuuxczFqUbmrXlui3g="
env:
  secure: "SmNN3GacsjH7Z1fpRzHI6F6sXom1nyAP6ihhqjwNGRKkH9LHvDWTnxxMdHdGViCCp7eE1tw+8bjxMQI8w2HnZdGb8+rCYVnXg0W3rcF/UJzfzsrgqXNtAFM2BqGpxku59/FuU4z9gHwlq+tekRJMW/I3xhD+DX5OU3fmpkau8oW2wXPRx6gfI0zQfw2Xy51qoCJMzCTtQto45slSWEGXuaBpAnlOY3ZP8DJtF+tiFEpl6LuiG+qa98PcwvfxZ468wWA9CdawK4SSCP2gKwxZNXnIL89Y3MKwv/Jv5qPQur3f+MIUR9J7SJVvHiC3d/50BgGNvNrrJ4ARO+Av2rXp2tAcl1Z9CA1KE28RVMaR441PUh/eoJNHeahj+uYCa4403QrQ84ZT88iTEDMRCT6FV7d5lKqxe/BJwbmivnTBphoa7v8BDMb0pZanDD1HbT05n23pLso7nl57FtXMdFCtcCP3hUR2KkIqbKyy68XIcix0jxeEyej0lqiYNkHX+F5H0bfuHYVTRzlncnut+6Yd4S/BO4U1JIZof84ME+4t5sVPWMm9LFSF9j2mtu03ZJYWQ3CpjVYekmKCXeOK7ZGHRY4XYqZbQsKNSb/vdaaPn0RJIIXSCW9dqzZvNDIuTL2aF0xDVnEcD7OnJrr7/lJg/V8r1rNqX44Mf49VnxV+zK4="
