// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @memberof module:pon-demo-site/conf.locales
 * @namespace en
 * @description en locales
 */
'use strict'

const app_ = require('./app.json')
const buttons_ = require('./buttons.json')
const errors_ = require('./errors.json')
const messages_ = require('./messages.json')
const org_ = require('./org.json')
const titles_ = require('./titles.json')
const toasts_ = require('./toasts.json')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.app = app_
exports.buttons = buttons_
exports.errors = errors_
exports.messages = messages_
exports.org = org_
exports.titles = titles_
exports.toasts = toasts_

module.exports = {
  app: app_,
  buttons: buttons_,
  errors: errors_,
  messages: messages_,
  org: org_,
  titles: titles_,
  toasts: toasts_,
}
