// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Db resource classes
 * @memberof module:pon-demo-site/server.db
 * @namespace resources
 */
'use strict'

const UserResource_ = require('./UserResource')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.UserResource = UserResource_

module.exports = {
  UserResource: UserResource_,
}
