// Code generated by coz. DO NOT EDIT.
/**
 * Act mapping
 * @memberof mappings
 * @namespace ActMapping
 */
'use strict'

const ac = require('../actions')

module.exports =
  /** mappings.ActMapping */
  {
    appAct: ac.AppAct,
    connectionRetryAct: ac.ConnectionRetryAct,
    homeAct: ac.HomeAct,
    locationAct: ac.LocationAct,
    toastAct: ac.ToastAct,
  }

Object.freeze(module.exports)
