// Code generated by coz. DO NOT EDIT.
/**
 * @description Module mappings
 * @memberof module:pon-demo-site/client
 * @namespace mappings
 */
'use strict'

const ActMapping_ = require('./ActMapping')
const SceneMapping_ = require('./SceneMapping')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.ActMapping = ActMapping_
exports.SceneMapping = SceneMapping_

module.exports = {
  ActMapping: ActMapping_,
  SceneMapping: SceneMapping_,
}
