// Code generated by coz. DO NOT EDIT.
/**
 * @description Module mappings
 * @memberof module:pon-demo-site/client
 * @namespace mappings
 */
'use strict'

const ActMapping_ = require('./ActMapping')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.ActMapping = ActMapping_

module.exports = {
  ActMapping: ActMapping_,
}
