// Code generated by coz. DO NOT EDIT.
/**
 * Scene mapping
 * @memberof mappings
 * @namespace SceneMapping
 */
'use strict'

const sc = require('../scenes')

module.exports =
  /** mappings.SceneMapping */
  {
    homeScene: sc.HomeScene,
  }

Object.freeze(module.exports)
