// Code generated by coz. DO NOT EDIT.
/**
 * @description Action modules
 * @memberof module:pon-demo-site/client
 * @namespace actions
 */
'use strict'

import AppAct from './AppAct'
import ConnectionRetryAct from './ConnectionRetryAct'
import HomeAct from './HomeAct'
import LocationAct from './LocationAct'
import ToastAct from './ToastAct'

export {
  AppAct,
  ConnectionRetryAct,
  HomeAct,
  LocationAct,
  ToastAct,
}

export default {
  AppAct,
  ConnectionRetryAct,
  HomeAct,
  LocationAct,
  ToastAct,
}
