// Code generated by coz. DO NOT EDIT.
/**
 * @description Scene classes
 * @memberof module:pon-demo-site/client
 * @namespace scenes
 */
'use strict'

import HomeScene from './HomeScene'

export {
  HomeScene,
}

export default {
  HomeScene,
}
