// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
/**
 * @description Fragment components
 * @memberof module:pon-demo-site/client
 * @namespace stateless
 */
'use strict'


export {
}

export default {
}
