// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
'use strict'

import React from 'react'
import {
  ConnectionRetryDialog,
} from '../stateful'

/**
 * Dialogs Component
 * @memberof module:pon-demo-site/client
 * @function Dialogs
 */
const Dialogs = React.memo(() =>
  (
    <React.Fragment>
      <ConnectionRetryDialog />
    </React.Fragment>
  )
)

export default Dialogs
