// Code generated by coz. DO NOT EDIT.
/**
 * Dialogs Component
 * @memberof ui
 * @function Dialogs
 */
'use strict'

import React from 'react'
import {
  ConnectionRetryDialog,
} from '../stateful'

/** @lends ui.Dialogs */
const Dialogs = React.memo(() =>
  (
    <React.Fragment>
      <ConnectionRetryDialog />
    </React.Fragment>
  )
)

export default Dialogs
