// Code generated by coz. DO NOT EDIT.
'use strict'

import Dialogs from './Dialogs'
import Footer from './Footer'
import Header from './Header'
import Toasts from './Toasts'

export {
  Dialogs,
  Footer,
  Header,
  Toasts,
}

export default {
  Dialogs,
  Footer,
  Header,
  Toasts,
}
