// Code generated by coz. DO NOT EDIT.
/* eslint-disable */
'use strict'


import abstractCall_ from './abstract/call.json'
import abstractDetail_ from './abstract/detail.json'
import abstractFilter_ from './abstract/filter.json'
import abstractHash_ from './abstract/hash.json'
import abstractInput_ from './abstract/input.json'
import abstractList_ from './abstract/list.json'
import abstractProcess_ from './abstract/process.json'
import app_ from './app.json'
import connectionRetry_ from './connection/retry.json'
import home_ from './home.json'
import location_ from './location.json'
import toast_ from './toast.json'

/**
 * Scopes
 * @memberof module:pon-demo-site/client
 * @namespace scopes
 */
const scopes = {}

scopes.abstract = {}
scopes.abstract.call = abstractCall_
scopes.abstract.detail = abstractDetail_
scopes.abstract.filter = abstractFilter_
scopes.abstract.hash = abstractHash_
scopes.abstract.input = abstractInput_
scopes.abstract.list = abstractList_
scopes.abstract.process = abstractProcess_
scopes.app = app_
scopes.connection = {}
scopes.connection.retry = connectionRetry_
scopes.home = home_
scopes.location = location_
scopes.toast = toast_

export default scopes
